# fly.toml app configuration file generated for brainmate on 2025-01-04T02:04:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brainmate'
primary_region = 'fra'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.1'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

# Define processes for the application
[processes]
  app = "php artisan serve --port=8080"  # Process for serving the web application
  worker = "php artisan queue:work"      # Process for handling queued jobs

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]  # Only the 'app' process belongs to the HTTP service

# Worker service configuration (separate from HTTP service)
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["worker"]  # The 'worker' process runs separately
  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Mount the volume for persistent storage (optional, uncomment if needed)
#[mounts]
#  source = "attachments"
#  destination = "/var/www/html/storage/app/uploads"